version: "2"
services:
  web:
    build: .
    image: ctfhub/challenge_wangdingbei_2020_web_qinglong_notes
    restart: always
    ports:
      - "8083:80"
    environment:
      - FLAG=ctfhub{challenge_wangdingbei_2020_web_qinglong_notes}
